// Archivo de traducciones para Estudiame
// Puedes agregar más idiomas siguiendo el mismo formato

const translations = {
  es: {
    title: 'Estudiame',
    fileLabel: 'Archivo de preguntas (.txt):',
    durationLabel: 'Duración del examen (minutos):',
    passLabel: 'Porcentaje de aprobación (%):',
    startBtn: 'Iniciar examen',
    prevBtn: 'Anterior',
    showAnswerBtn: 'Mostrar respuesta',
    nextBtn: 'Siguiente',
    progress: 'Progreso',
    timer: '⏰',
    footer: 'Estudiame — 2025 &mdash; Hecho con ❤️ para el estudio personal<br><a href="https://github.com/MrJhonny/studyme" target="_blank" rel="noopener" class="d-inline-flex align-items-center gap-2 text-decoration-none text-secondary fw-semibold"><img src="https://icones.pro/wp-content/uploads/2021/06/icone-github-grise.png" alt="GitHub MrJhonny" style="height:32px; width:32px; border-radius:50%; box-shadow:0 2px 8px #0002;"> <span>MrJhonny en GitHub</span></a>',
    timeoutTitle: '¡Tiempo agotado!',
    timeoutBody: 'El tiempo del examen ha finalizado. El total de tu examen ha sido evaluado.<br>Todas las respuestas sin contestar se consideran incorrectas.',
    timeoutAccept: 'Aceptar',
    // Validaciones & summary
    valFile: 'Por favor selecciona un archivo de preguntas.',
    valDuration: 'Duración inválida.',
    valPass: 'Porcentaje de aprobación inválido.',
    valNoQuestions: 'No se encontraron preguntas válidas en el archivo.',
    summaryTitle: 'Resumen de respuestas',
    qLabel: 'Pregunta',
    timeUsed: 'Tiempo usado',
    seconds: 'segundos',
    finalScore: 'Puntaje final',
    approved: '¡Aprobado! 🎉',
    notApproved: 'No aprobado',
    yourPick: '(tu selección)',
    correct: '(correcta)',
  },
  en: {
    title: 'StudyMe',
    fileLabel: 'Questions file (.txt):',
    durationLabel: 'Exam duration (minutes):',
    passLabel: 'Passing score (%):',
    startBtn: 'Start exam',
    prevBtn: 'Previous',
    showAnswerBtn: 'Show answer',
    nextBtn: 'Next',
    progress: 'Progress',
    timer: '⏰',
    footer: 'StudyMe — 2025 &mdash; Made with ❤️ for personal study<br><a href="https://github.com/MrJhonny/studyme" target="_blank" rel="noopener" class="d-inline-flex align-items-center gap-2 text-decoration-none text-secondary fw-semibold"><img src="https://icones.pro/wp-content/uploads/2021/06/icone-github-grise.png" alt="GitHub MrJhonny" style="height:32px; width:32px; border-radius:50%; box-shadow:0 2px 8px #0002;"> <span>MrJhonny on GitHub</span></a>',
    timeoutTitle: 'Time is up!',
    timeoutBody: 'The exam time is over. Your exam has been graded.<br>All unanswered questions are considered incorrect.',
    timeoutAccept: 'OK',
    // Validations & summary
    valFile: 'Please select a questions file.',
    valDuration: 'Invalid duration.',
    valPass: 'Invalid passing score.',
    valNoQuestions: 'No valid questions found in the file.',
    summaryTitle: 'Answers summary',
    qLabel: 'Question',
    timeUsed: 'Time used',
    seconds: 'seconds',
    finalScore: 'Final score',
    approved: 'Passed! 🎉',
    notApproved: 'Not passed',
    yourPick: '(your pick)',
    correct: '(correct)',
  },
  fr: {
    title: 'ÉtudieMoi',
    fileLabel: 'Fichier de questions (.txt):',
    durationLabel: "Durée de l'examen (minutes):",
    passLabel: 'Pourcentage de réussite (%):',
    startBtn: "Commencer l'examen",
    prevBtn: 'Précédent',
    showAnswerBtn: 'Afficher la réponse',
    nextBtn: 'Suivant',
    progress: 'Progression',
    timer: '⏰',
    footer: 'ÉtudieMoi — 2025 &mdash; Fait avec ❤️ pour les études personnelles<br><a href="https://github.com/MrJhonny/studyme" target="_blank" rel="noopener" class="d-inline-flex align-items-center gap-2 text-decoration-none text-secondary fw-semibold"><img src="https://icones.pro/wp-content/uploads/2021/06/icone-github-grise.png" alt="GitHub MrJhonny" style="height:32px; width:32px; border-radius:50%; box-shadow:0 2px 8px #0002;"> <span>MrJhonny sur GitHub</span></a>',
    timeoutTitle: 'Temps écoulé !',
    timeoutBody: "Le temps de l'examen est terminé. Votre examen a été évalué.<br>Toutes les questions non répondues sont considérées comme incorrectes.",
    timeoutAccept: 'OK',
    // Validations & summary
    valFile: 'Veuillez sélectionner un fichier de questions.',
    valDuration: 'Durée invalide.',
    valPass: 'Pourcentage de réussite invalide.',
    valNoQuestions: 'Aucune question valide trouvée dans le fichier.',
    summaryTitle: 'Résumé des réponses',
    qLabel: 'Question',
    timeUsed: 'Temps utilisé',
    seconds: 'secondes',
    finalScore: 'Score final',
    approved: 'Réussi ! 🎉',
    notApproved: 'Non réussi',
    yourPick: '(votre choix)',
    correct: '(correcte)',
  }
};
